// app/layout.js
import Link from 'next/link';
import './globals.css';

// This metadata changes the tab title in your browser
export const metadata = {
  title: 'My First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: 'sans-serif' }}>

        {/* --- START OF SHARED NAVBAR --- */}
        <nav style={{ padding: '20px', backgroundColor: '#333', color: 'white' }}>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/blog/my-awesome-post">Blog</Link>
          <Link href="/counter">Counter</Link>
          <Link href="/todo">Task Master</Link>
          <Link href="/pokemon">Pokemon</Link>
        </nav>
        {/* --- END OF SHARED NAVBAR --- */}

        {/* This "children" prop is where your page.js content goes */}
        <main style={{ padding: '20px' }}>
          {children}
        </main>

      </body>
    </html>
  )
}